//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int user_id { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    
        public virtual REGISTER REGISTER { get; set; }
    }
}
